dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  # NOVAS DEPENDÊNCIAS PARA UPDATE AUTOMÁTICO
  dio: ^5.4.0  # Para download com progress
  path_provider: ^2.1.1  # Para acessar diretórios
  permission_handler: ^11.1.0  # Para gerenciar permissões
  install_plugin: ^2.1.0  # Para instalar APK automaticamente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true