name: finance_app_new
description: "Aplicativo de gerenciamento financeiro"
publish_to: "none"

version: 0.0.0+13

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  dio: ^5.4.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  app_links: ^6.3.2
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  file_picker: ^8.1.7
  open_filex: ^4.7.0
  fl_chart: ^0.68.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/


